[abs.cha]
bonus = 0
score = 12
[abs.con]
bonus = 0
score = 11
[abs.dex]
bonus = 1
score = 15
[abs.int]
bonus = 0
score = 12
[abs.str]
bonus = 1
score = 13
[abs.wis]
bonus = 0
score = 11
[bio]
level = 1
name = "Geoff"
role = "Specialist"
[skl]
architecture = 1
bushcraft = 1
climb = 1
languages = 1
search = 1
sleight_of_hand = 2
sneak_attack = 2
stealth = 1
tinker = 3
