[abs.cha]
bonus = 0
score = 11
[abs.con]
bonus = -1
score = 8
[abs.dex]
bonus = -1
score = 7
[abs.int]
bonus = 0
score = 12
[abs.str]
bonus = -1
score = 8
[abs.wis]
bonus = 0
score = 11
[bio]
level = 1
name = "Omadon"
role = "Magic-user"
